<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UserManagement.Domain\UserManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\Commands\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Common\DTOs\" />
    <Folder Include="Users\Commands\" />
    <Folder Include="Users\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
